### ISSUE TITLE
Usage Clarification

### ISSUE THREAD

**Issue by DivaVocals** [ericakfranz/genesis-off-canvas-menu#1]
Do I take it that all I need to do is to upload the "genesis-off-canvas-menu" folder to my site's plugins directory is all I need to do to test out using this??

**Comment by ericakfranz** [comment]
This is setup to be included in a child-theme for testing, see http://fatpony.me/genesiswp/adding-canvas-menu-genesis-theme/ for a walk-through of each section.

You can copy the /js/ directory into your child-theme's directory, then copy the functions.php code into your child-theme's functions.php file, and the same with the style.css code - copy that into your child-theme's style.css file.
